name: Build Site

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Docker Build
              run: docker build -t igorbonfim/shorturl-site:latest .

            - name: Login Docker Hub
              uses: docker/login-action@v2
              with:
                username: igorbonfim
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Push image to DockerHub
              run: docker push igorbonfim/shorturl-site:latest